name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docker/**'
      - '.github/**'
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run Tests
        run: |
          nix-build tests/default.nix -A static
          nix-build tests/default.nix -A vmtest

      - name: CI Completion
        if: always()
        run: echo "CI tests completed."
